name: Maven Test and Deploy Snapshot
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -DnewVersion=1.0-SNAPSHOT -B package -Dmaven.test.skip=true
      - name: Test with Maven
        run: mvn -B test
      - name: Deploy to maven.gilmoh.de with Maven
        run: mvn deploy -B -DnewVersion=1.0-SNAPSHOT -s build/settings.xml -Dmaven.test.skip=true
        env:
          DEPLOYMENT_USERNAME: ${{ secrets.NEXUS_BOT_USERNAME }}
          DEPLOYMENT_PASSWORD: ${{ secrets.NEXUS_BOT_PASSWORD }}
